services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
